version: "3.8"
services:
  proxy:
    image: traefik:v2.9
    command:
      - "--api=true"
      - "--api.dashboard=true"
      - "--api.insecure=true" 
      - "--providers.docker"
      - "--entrypoints.web.address=:80"
    labels: {}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host

  fetch:
    container_name: efishery-fetch-service
    build: 
      context: ./fetch-service/
      dockerfile: ./Dockerfile
    labels: 
      - "traefik.http.routers.product.middlewares=auth"
      - "traefik.http.routers.product.rule=PathPrefix(`/commodities/`)"
      - "traefik.http.services.product.loadbalancer.server.port=9000"

  auth:
    container_name: efishery-auth-service
    build: ./auth-service/
    labels: 
      - "traefik.http.middlewares.auth.forwardauth.address=http://auth:9000/auth/authorize"
      - "traefik.http.middlewares.auth.forwardauth.trustForwardHeader=true"
      - "traefik.http.routers.auth.rule=PathPrefix(`/auth/`)"
      - "traefik.http.services.auth.loadbalancer.server.port=9000"

